version: "2"
services:
  diagnostics:
    image: openlmis/diagnostics
    links:
      - log
    ports:
      - "8080"
    env_file: .env
  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/diagnostics:/var/log'
